### PR TITLE
Upgrade project to N-API for better ABI stability in Node

### PR DESCRIPTION
**Pull request by implausible**
This PR switches the project from leveraging [Native Abstractions for Node.js](https://github.com/nodejs/nan) to [N-API](https://nodejs.org/api/n-api.html) using [Node-Addon-Api](https://github.com/nodejs/node-addon-api) for C++. This is to solve the recurring issues that NAN projects run into with ABI stability. In particular, when loading this library in Electron 7.1.2 we are receiving the error: `(node:26305) Electron: Loading non context-aware native modules in the renderer process is deprecated and will stop working at some point in the future, please see https://github.com/electron/electron/issues/18397 for more information`.

When installing Node-Addon-Api, I enabled exceptions in C++ and the exception handling for Node-Addon-Api so that writing the extension doesn't require checking error codes after every operation.

No changes have been made to the external API.

### CODE REVIEW

**Comment by dachev** [comment]
@implausible Thank you for the PR. This is a great contribution! Can you take a look at the Windows build errors here: https://ci.appveyor.com/project/dachev/node-cld/builds/30456788? The Appvetor integration was broken when the PR was submitted so it didn't trigger an error when it should have. If you can fix those I'll be happy to merge and make a new release without any delay.

**Comment by implausible** [comment]
Yes, I'll take a look at that. Thanks for pointing that out.

**Comment by implausible** [comment]
Some suggestions to start before digging too far into this. The AppVeyor builds are currently building against some incredibly old versions of Node that are no longer maintained by the Node team. Here's the current LTS schedule for Node. Currently Node 8 has just left it's maintenance period and we should consider killing support for Node 8.

That said, we should be able to support Node > 8.16.0 reasonably, as that would land us at version 4 of N-Api. With that in mind. I'll take a look at addressing the issues with 10 and 12, and hopefully bring along 8.16.0 with me.

**Comment by dachev** [comment]
Supporting node 8.16.0+ will be great but I'll be content even with 10+. Thanks!

**Comment by implausible** [comment]
So in my investigation. I've discovered that https://github.com/dachev/node-cld/commit/beff30eb6413290837f30979073e5d4e8a7a2ae5 is the commit that broke the tests on windows. There are a few tests that no longer return reliable results cross-platform after this CLD2 upgrade.

I can confirm without a doubt that this PR does not change support from the previous release. I also recommend we consider bumping from CLD2 to CLD3 to see if these tests become more reliable cross-platform after the upgrade.

That said, I believe the appveyor.yml I've updated should provide better / running testing on AppVeyor. I've also added Node 8 and 10 to the Travis suite.

I had to go allll the way back to 0.12.18 to confirm which commit actually broke these tests though. :)

**Comment by dachev** [comment]
CLD3 is the ultimate goal. I have been planning to work on that for a while but my schedule has been full. It wouldn't get any better expecting a child soon :-) Realistically, I'll probably get to it in the second half of the year. Until then, I am happy with killing the testes for those select few languages on Windows.

Thank you for the hard work!

**Comment by implausible** [comment]
@dachev Gratz on the child :smile:. Any chance you can get a release going for cld on npm in the near future? Don't worry about any weekend work, though :stuck_out_tongue:

**Comment by dachev** [comment]
@implausible I published 2.6.0.

**Pull request merged**
