### PR TITLE
Build correctly in VS2015

### PR DESCRIPTION
**Pull request by paulcbetts**
I have no idea how other projects don't hit this, but /shrug

### CODE REVIEW

**Comment by mjeries** [comment]
I was able to resolve #32 with this PR.

**Comment by dachev** [comment]
@paulcbetts Appveyor builds are still failing. Do you know why this might be?

**Comment by paulcbetts** [comment]
@dachev Nope, they fail on master too

**Comment by dachev** [comment]
@paulcbetts I see. This is resolving a different issue. Thanks for your help and patience.

**Pull request merged**
