### PR TITLE
Node 12 compatibility

### PR DESCRIPTION
**Pull request by andreas**
With these changes, I can install the package locally using Node v12.0.0.

I'm no V8 expert, but used the following sources to come up with this patch:

- https://github.com/bcoin-org/bcrypto/issues/7
- https://github.com/sass/node-sass/issues/2632#issuecomment-486186423
- https://github.com/nodejs/node/issues/18909

### CODE REVIEW

**Comment by andreas** [comment]
It builds on Travis with Node v8, v10 and v12, but fails with older versions.

**Comment by holm** [comment]
@dachev any chance you could review this PR, as it is blocking us upgrading to Node 12

**Comment by dachev** [comment]
@andreas @holm Thank you so much for the fix and I apologize for the long delay. Tested, merged and released!

**Comment by holm** [comment]
Excellent, thanks a lot.

**Comment by andreas** [comment]
Thanks @dachev!

**Comment by holm** [comment]
I was just testing this, and it doesn't seem like the right code got published. On node 12:

* `npm install cld@2.5.0` fails like before this PR
* `npm i cld@https://github.com/dachev/node-cld#4ef203d718e2603aeefd477a146a4c7a32bf32a8` works

**Comment by dachev** [comment]
@holm Thanks for catching this. I pushed 2.5.1 and this time I confirmed that it actually installs.

**Pull request merged**
